target: pl_modules.smamba_module.SMambaModule
params: 
    num_features: 6
    seq_len: 14
    use_norm: True
    d_model: 128
    d_state: 32
    d_ff: 128
    dropout: 0.1
    activation: 'gelu'
    e_layers: 2
    loss: 'mse'
normalize: False