data_config: 'mode_1'
model: 'GRU_nv'

name: 'gru'
max_epochs: 700
use_volume: False

hyperparams:
    optimizer: 'adam'
    lr: 0.005
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001